### ISSUE TITLE
Espace manquante dans un exemple de lien

### ISSUE THREAD

**Issue by JulienPalard** [vpoulailleau/support-traduction-doc-python#1]
Alors j'ignore si le parseur RST le mange telle quelle, mais dans :

    `Lien Wikipedia<https://en.wikipedia.org/wiki/reStructuredText>`_

j'en mettrait une entre `Wikipedia` et `<`.

**Comment by vpoulailleau** [comment]
J'ai pas trouvé l'info de si c'est obligatoire ou pas, mais effectivement dans les exemples ils mettent une espace : http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#embedded-uris-and-aliases

J'ai testé avec des éditeurs en lignes, visiblement ils n'aiment pas le manque d'espace. http://rst.aaroniles.net/ me signale une erreur de syntaxe :

```
System Message: ERROR/3 (<string>, line 1); backlink
Unknown target name: "lien wikipedia<https://en.wikipedia.org/wiki/restructuredtext>".
```

Je vais corriger le support.
