### ISSUE TITLE
Liens IRI

### ISSUE THREAD

**Issue by JulienPalard** [vpoulailleau/support-traduction-doc-python#2]
Tu as mis quelques liens comme :

    https://git-scm.com/book/fr/v2/D%C3%A9marrage-rapide-Installation-de-Git

Tu pourrais les écrire comme ça :

    https://git-scm.com/book/fr/v2/Démarrage-rapide-Installation-de-Git

Déjà c'est plus lisible, plus joli, et plus facile à écrie (ils ne pourront pas cliquer dessus).

Aussi c'est tout à fait légitime, c'est une IRI, pour `Internationalized Resource Identifier`, et la conversion vers les URI est bien définie et respectée par les navigateurs : https://tools.ietf.org/html/rfc3987#section-3.1

Bien sûr l'URL aurait contenu `D%E9marrage-rapide-Installation-de-Git`, tu aurai été obligé de la conserver sous forme d'URL.

**Comment by vpoulailleau** [comment]
Je découvre les IRI, merci pour l'info. Je vais mettre à jour.
